Data mahdiislam79 chunk9 cleanup
mir-abir-hossain/real-history-of-Bangladesh pull request #30
Opened 2024-09-05 14:10 UTC by mahdiislam79

2024-09-06 06:57 UTC, dg1223 requested changes
Good work. Please fix the following:

16: পাঁটি
373: হুল্লোড়্রের
398: দুঃশ্চিত্তামুক্ত
1036: জামনীর
1364: ইন্টেলিজেঙ্গের
1940: করেছিলেন।
1989: ট্রুপসদের

2024-09-06 22:16 UTC, mahdiislam79 commented
> Good work. Please fix the following:
> 
> 16: পাঁটি 373: হুল্লোড়্রের 398: দুঃশ্চিত্তামুক্ত 1036: জামনীর 1364: ইন্টেলিজেঙ্গের 1940: করেছিলেন। 1989: ট্রুপসদের

fixed them.

2024-09-07 01:18 UTC, dg1223 requested changes
This one is still pending. The rest looks good.

1989: ট্রুপসদের -> ট্রূপসদের

2024-09-07 08:36 UTC, mahdiislam79 commented
> This one is still pending. The rest looks good.
> 
> 1989: ট্রুপসদের -> ট্রূপসদের

Sorry vai didn't notice it. It's fixed as well.

2024-09-07 10:35 UTC, dg1223 approved these changes
Good work, thanks! Closing #20

2024-09-07 10:35 UTC, merged