যা_দেখেছি_যা_বুঝেছি_যা_করেছি_10_clean
mir-abir-hossain/real-history-of-Bangladesh pull request #32
Opened 2024-09-07 20:03 UTC by amitsingha

### **_যা_দেখেছি_যা_বুঝেছি_যা_করেছি_10_clean_**

> 
> নীতিসমূহ ও পদক্ষেপগুলি প্রশংসিত হয়। সার্বিক অবস্থার স্বাভবিকরণের পর সেনা
> পরিষদ বিপ্লবের অবশিষ্ট উদ্দেশ্যাবলী বাস্তবায়নের প্রচেষ্টায় ব্রতী হন। লোকচক্ষুর
> প্রচেষ্টায় । পর্বত সমান প্রতিবন্ধকতার মুখে কাজ করতে হচ্ছিল সেনা পরিষদকে ।
> বস্তুতঃ শেখ মুজিব তার লিজের ও পরিবারের ক্ষমতাকে চিরস্থায়ী একটা ভিত্তি দেয়ার
> লক্ষ্যেই বাকশালী স্বৈরাচার কায়েম করেছিলেন। এভাবেই যুগযুগ ধরে স্বৈরাচারী
> শাসকরা আর্বিভূত হয়। এরা একই নিয়মে ক্ষমতা কুক্ষিগত করে৷ জামানীর
> হিটলারের উত্থান ঘটেছিল এভাবেই ৷ নাৎসী পার্টি তাকে মহামানব আখ্যায়িত
> করেছিল । বাকশালীরাও শ্লোগান তুলেছিল, “এক নেতা, এক দেশ, বঙ্গবন্ধুর
> বাংলাদেশ ।” ফলশ্রুতিতে মুজিব পরিণত হয়েছিলেন, একজন স্বেরাচারী রাষ্ট্রনায়কে ৷
> ইটালীতে মুসোলিনির আবির্ভাবও ঘটেছিল একই প্রক্রিয়ায় ৷

2024-09-09 05:17 UTC, dg1223 requested changes
Please fix all of these issues.

6: লিজের
24: পাচাঁর
31: কাভ, এঁতিহাসিক
37: নিরনন
49: কীচামাল
53: লাঞ্ছুণার -> লাঞ্ছনা
80: বাঁচানোর -> বাচানোর
91-92: page 499 from the book is missing entirely; maybe you can put this page into the OCR notebook instead of writing everything by yourself.
100-101:  an entire line is missing after সর্বদলীয় সরকার
108-109: an entire line is missing after নতুন করে জাতীয়
109: রক্ষমীবাহিনীর
112: কমান্ত
124: এঁক্য
147: বাকশালপদ্থী
173: বরক্ষীবাহিনীর
186: এঁক্য
229: লিফ্স্মূলজ
234: মুজিবপছ্থী
247: সন্ত্স্ত
258: হ্বে
269: THF
270: সংখ্রামীদের
290: বর্িপ্রকাশ
301: ভুলত্রান্তি
306: র্ন্দলীয়
327: দৃড়
341: অত্যস্ত, সং
342: উদারপদ্থী
343: অস্ধভক্তি
357: ব্রগেডিয়ার
368: ডাবতেও
412: ওুদ্ধত্য
470: এঁক্যের
471: এঁক্যবদ্ধ
478: একফ্রন্ট
480: স্ভষ্টি
488: এঁক্যবদ্ধভাবে, কাধ
494: অভিনু
512: বিৰিত
530: ace
531-532: an entire line is missing after আমার কথার ধরণ
534: র্যাঙ্কের
548: রিরপ্পোটটা
549: ভূয্না
551: স্বটানো
553: হয়েছিল জমরাও
555: কন্ট্রোল
568: দুঁ্নীতিবাজরা
570: বল্ছো
576: ০1080
600: পনিবেশিক
603: গঁপনিবেশিক
606: এঁ
633: প্রকারস্তরে
642: ফীঁকটিও
715: পটন
734: কযম্যুনিষ্ট
735: তীক্ন
749: চুড়াস্তভাবে
814: ত্রাস্তিলগ্নেও
815: শাস্তির
818: স্টেটসূম্যান
826: বিপ্রবীদের
835: লাথ্চের
836: রেশ
839: অন্দি
841: 116081০০0০0
851: ব্যাপারটাকে (। - dari missing), নিশ্মীকে
854: তামার
874-875: an entire line is missing after চলে যেতে ৷ কর্নেল
878: 110৩
880: না না
884: নিম্থমীই
886: কন্ট্রোল
910: নিমশ্মী
929: ইন্তাষ্ট্রিয়াল
930: বিভিনন
949: ,
951: আস্তরিকতার
954: wag
967: চক্রু, ট্রপসদের
982: সেন্ট্রি
989: ট্রপসরা
990: 10
994: বিক্ফোরন
1014: 11
1015: DTS, |
1016: St# G@red!
1020: |
1024: ড৪৭
1028: Daliny
1032: TTS
1035: .
1068: জন্যেছিল
1068: প্রস্ত ণব (merge it as প্রস্তাব on line 1068 and delete ণব from 1069)
1069: ন্‌
1088: ts
1104: ট্রপস
1118: বিক্ষোরন
1146: পরিস্কিতি
1156: aoa
1160: Continuetion  (incorrect in the main book) -> Continuation
1164: মতানৈকা
1170: বিগেডিয়ার
1170-1171: an entire line is missing after নিয়ে এয়ারফোর্স
1171: জেনে
1182: ব্রস্তপায়ে
1190: এঁ, হাস্যকৃর
1198: বিত্রদ্ধ্য
1198-1199: an entire line is missing after বলেই
1235: ংকা
1246: তোয়াৰ
1262: Stata
1277: rio
1278: ferarecwa
1288: FAS Hr
1293: অত্যস্ত
1293-1294: an entire line is missing after সময়ের চাহিদার
1294: সুষ্ষ্ম, বগেডিয়ার
1301-1302: an entire line is missing after জবাব শুনে
1313: ona
1328: মান্লাফ
1336: “2
1351: নিলে
1360: বিগেডিয়ার
1366: এঁক্যের
1372: !
1374-1375: বাস্ত ame (merge it as বাস্তবায়নে on line 1374 and delete ame from 1375)
1390: সেলু্যুট
1402: |
1422: তীক্ষম
1472: !
1480: ।
1496: ৩তরা
1506: উঠেছিলাম।
1508: এঁ
1511: এগুলে (mistake in book) -> এগুল, সাহসিকত!, হয়তে!
1513: জাষ্টরিস
1520: করেন।
1524: expose
1527: বিষয়ে।
1531: এঁক্যবদ্ধভাবে
1548-1549: an entire line is missing after তাই কথা
1563: ব্বিগেডিয়ার
1570: বীচিয়ে
1571: গ৩রা
1574, 1579, 1601, 1605, 1664, 1681, 1683, 1684: ', এঁতিহাসিক
1575: ছিননভিনন
1584: aR -> ঐক্য।
1585: সমর
1598: এঁদিনই
1603: অজ্বুথান
1606: অভ্যুথানের
1627: প্রধাগতভাবে
1641: এঁ
1643: ” -> ।”
1648: চূড়াস্ত
1654: সুষ্ঠ
1658: * -> '
1666: করিয়াছেন।
1667: অনাড়ঙ্তর
1670: অকুষ্ঠ
1674: উর্ধ্ধকালে
1677: সশঙ্ত্র, এঁতিহাসিক
1678: শাসকচক্রু
1680: হত্তক্ষেপকে
1681: লিন্সার
1689: , (remove this)
1706: বৈগ্নবিক
1709: সর্বমুগে
1711: করতে।
1723: প্রস্তরে -> প্রান্তরে

2024-09-11 04:11 UTC, amitsingha commented
ok vi.

2024-09-12 07:51 UTC, dg1223 commented
@amitsingha I know this is the second chunk you're working on. if possible, please finish the corrections by this weekend. thank you!

2024-09-13 18:56 UTC, dg1223 reviewed
Great job! thanks for the hard work. There are a few more issues below but I'll fix them myself.

4: লোকচক্ষুর (keep it, it was correct)
53: লাঞ্ছনা -> লাঞ্ছনার (sorry, i didn't give you the complete word)
99: এহণ -> গ্রহণ
434: ওদ্ধত্য -> ঔদ্ধত্য
836: স্টেটসূম্যান -> স্টেটসম্যান
843: বিপ্রবীদের -> বিপ্লবীদের
966: ,
1045: is’nt -> isn't
1189: জেনে তক্ষুনি Air traffic
1217: ব্রিগেডিয়ার খালেদ, কর্নেল শাফায়াত, মেজর হাফিজ, ক্যাপ্টেন ইকবাল, ক্যাপ্টেন
1313: আটা -> আঁটা
1492: আলোচনা! -> আলোচনা
1500: অনাস্থা। -> অনাস্থা
1687: করিয়াছেন -> করিয়াছেন।
1744: প্রস্তরে -> প্রান্তরে

2024-09-13 19:18 UTC, dg1223 commented
Closing this PR now as it is continued on #46

2024-09-13 19:18 UTC, closed without merging